<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://cargo.com/soap/price"
    xmlns:tns="http://cargo.com/soap/price"
    elementFormDefault="qualified">

    <xs:element name="verifierPrixRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prixPropose" type="xs:decimal"/>
                <xs:element name="nombrePlaces" type="xs:int"/>
                <xs:element name="distanceKm" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="verifierPrixResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prixRecommande" type="xs:decimal"/>
                <xs:element name="statut" type="xs:string"/>
                <xs:element name="message" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>